/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as PedidoIdRouteImport } from './routes/pedido/$id'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/admin/dashboard'
    | '/pedido/$id'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/admin/dashboard'
    | '/pedido/$id'
    | '/admin'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/admin/dashboard'
    | '/pedido/$id'
    | '/admin/'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  PedidoIdRoute: typeof PedidoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  PedidoIdRoute: PedidoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
